services:
  backend: 
    image: meet-backend
    build: ./Backend
    ports:
      - 8000:8000
  frontend:
    image: meet-frontend
    build: ./Frontend
    ports:
      - 8080:8080
  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     # - PGUSER=${DB_USER}
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     # - POSTGRES_DB=${DB_NAME}
  #     # - POSTGRES_DB=app
  #     # - POSTGRES_USER=postgres
  #     # - POSTGRES_PASSWORD=supersecretpassword
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - db-data:/var/lib/postgresql/data

volumes:
  db-data:
