"""initial2

Revision ID: 2b0a981991eb
Revises: 9d70b39d0650
Create Date: 2025-03-29 18:12:45.405194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b0a981991eb'
down_revision: Union[str, None] = '9d70b39d0650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_ts', sa.DateTime(), nullable=False),
    sa.Column('updated_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('interests', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('created_ts', sa.DateTime(), nullable=False),
    sa.Column('updated_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('comment')
    # ### end Alembic commands ###
