"""add-new-key

Revision ID: fcd6e3c9523d
Revises: 2b0a981991eb
Create Date: 2025-03-29 19:14:03.104833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd6e3c9523d'
down_revision: Union[str, None] = '2b0a981991eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'profile_id')
    # ### end Alembic commands ###
